# Site settings
name: Furkan K. Yıldırım
title: Furkan K. Yıldırım | Computer Scientist & Industrial Engineer
description: Master of Science Student at Sabancı University & Founder of Flio.ai with expertise in algorithms, software development, and optimization
url: https://furkankyildirim.com/
baseurl: ''
email: contact@furkankyildirim.com
cover: /img/og.png
# logo: /img/emojis/technologist.png
resume: /assets/files/resume.pdf
social:
  - title: email
    url: mailto:contact@furkankyildirim.com
  - title: twitter
    url: https://twitter.com/furkankyildirim
  - title: instagram
    url: https://instagram.com/furkankyildirim_
  - title: github
    url: https://github.com/furkankyildirim
  - title: linkedin
    url: https://www.linkedin.com/in/furkankyildirim

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
